<?php

namespace FragosoSoftware\FileConverter\Core\Conversion;

use FragosoSoftware\FileConverter\Contracts\Conversion\ConverterInterface;
use FragosoSoftware\FileConverter\Config\ConverterConfig;
use FragosoSoftware\FileConverter\Infrastructure\Conversion\LibreOfficeClient;

abstract class AbstractConverter implements ConverterInterface
{
    protected string $source;
    protected string $destination;
    protected ?ConverterConfig $config;
    protected ?LibreOfficeClient $libreOfficeClient;

    public function __construct(?string $source = null, ?string $destination = null)
    {
        $this->source = $source ?? '';
        $this->destination = $destination ?? '';
        $this->config = ConverterConfig::getInstance();
        $this->libreOfficeClient = new LibreOfficeClient($this->config);
    }

    abstract public function convert(string $sourcePath, string $destinationPath): void;

    public function convertFromBinary(string $binary): string
    {
        $input = tmpfile();
        $meta = stream_get_meta_data($input);
        $inputPath = $meta['uri'];

        fwrite($input, $binary);

        $outputPath = tempnam(sys_get_temp_dir(), 'conv_');

        $this->convert($inputPath, $outputPath);

        $result = file_get_contents($outputPath);

        unlink($outputPath);
        fclose($input);

        return $result;
    }

    public function convertFromBase64(string $base64): string
    {
        $binary = base64_decode($base64);

        $converted = $this->convertFromBinary($binary);

        return base64_encode($converted);
    }

    /**
     * Verifica se a função exec() está disponível e não desabilitada.
     */
    protected function isExecAvailable(): bool
    {
        if (!function_exists('exec')) {
            return false;
        }
        $disabled = explode(',', ini_get('disable_functions'));
        return !in_array('exec', array_map('trim', $disabled), true);
    }

    /**
     * Converte usando LibreOffice (suporta modo externo e interno)
     */
    protected function convertWithLibreOffice(string $sourcePath, string $destinationPath): void
    {
        // Verifica se deve usar modo externo
        if ($this->config->useExternalLibreOffice()) {
            $this->convertWithExternalLibreOffice($sourcePath, $destinationPath);
            return;
        }

        // Modo interno (tradicional)
        $this->convertWithInternalLibreOffice($sourcePath, $destinationPath);
    }

    /**
     * Converte usando LibreOffice externo (sidecar)
     */
    protected function convertWithExternalLibreOffice(string $sourcePath, string $destinationPath): void
    {
        if (!$this->libreOfficeClient->isAvailable()) {
            throw new \RuntimeException(
                'External LibreOffice service not available at ' . 
                $this->config->getLibreOfficeHost() . ':' . 
                $this->config->getLibreOfficePort()
            );
        }

        $this->libreOfficeClient->convert($sourcePath, $destinationPath);
    }

    /**
     * Converte usando LibreOffice interno (binário local)
     */
    protected function convertWithInternalLibreOffice(string $sourcePath, string $destinationPath): void
    {
        $soffice = $this->findLibreOfficeBinary();
        if ($soffice === null) {
            throw new \RuntimeException('LibreOffice binary not found.');
        }

        $outputDir = dirname($destinationPath);
        $this->ensureDirectoryWritable($outputDir);

        // Constrói o comando com escapes adequados
        $command = sprintf(
            '%s --headless --norestore --nodefault --nofirststartwizard --invisible --convert-to pdf --outdir %s %s',
            $soffice,
            escapeshellarg($outputDir),
            escapeshellarg($sourcePath)
        );

        $output = [];
        $returnCode = 0;
        exec($command, $output, $returnCode);

        if ($returnCode !== 0) {
            throw new \RuntimeException(
                'LibreOffice conversion failed. Command: ' . $command . ' Output: ' . implode("\n", $output)
            );
        }

        $generatedFile = $outputDir . DIRECTORY_SEPARATOR . pathinfo($sourcePath, PATHINFO_FILENAME) . '.pdf';

        if (!file_exists($generatedFile)) {
            throw new \RuntimeException('PDF file not generated by LibreOffice.');
        }

        if ($generatedFile !== $destinationPath) {
            if (!rename($generatedFile, $destinationPath)) {
                throw new \RuntimeException('Could not move generated PDF to destination.');
            }
        }
    }

    /**
     * Determina se é possível usar o LibreOffice para conversão
     */
    protected function canUseLibreOffice(): bool
    {
        if ($this->config->useExternalLibreOffice()) {
            return $this->libreOfficeClient->isAvailable();
        }
        
        return $this->isExecAvailable() && $this->findLibreOfficeBinary() !== null;
    }

    /**
     * Localiza o binário do LibreOffice no sistema.
     */
    protected function findLibreOfficeBinary(): ?string
    {
        // Se configurado explicitamente, usa o caminho
        $binaryPath = $this->config->get('libreoffice.binary_path');
        if ($binaryPath && file_exists($binaryPath)) {
            return $binaryPath;
        }

        $osFamily = PHP_OS_FAMILY ?? (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' ? 'Windows' : (PHP_OS === 'Darwin' ? 'Darwin' : 'Linux'));

        switch ($osFamily) {
            case 'Windows':
                return $this->findLibreOfficeOnWindows();
            case 'Darwin':
                return $this->findLibreOfficeOnMac();
            default:
                return $this->findLibreOfficeOnLinux();
        }
    }

    /**
     * Verifica se o arquivo de origem existe e pode ser lido.
     */
    protected function ensureFileReadable(string $path): void
    {
        if (!is_file($path) || !is_readable($path)) {
            throw new \RuntimeException("Arquivo de origem não encontrado ou sem permissão de leitura: {$path}");
        }
    }

    /**
     * Tenta encontrar um binário no PATH do sistema
     */
    protected function findBinaryInPath(string $binaryName): ?string
    {
        $output = [];
        exec("which {$binaryName} 2>/dev/null", $output, $returnCode);
        if ($returnCode === 0 && !empty($output[0])) {
            return $output[0];
        }

        $output = [];
        exec("command -v {$binaryName} 2>/dev/null", $output, $returnCode);
        if ($returnCode === 0 && !empty($output[0])) {
            return $output[0];
        }

        return null;
    }

    /**
     * Procura o LibreOffice em sistemas Linux/Unix.
     */
    protected function findLibreOfficeOnLinux(): ?string
    {
        $binary = $this->findBinaryInPath('soffice');
        if ($binary !== null) {
            return $binary;
        }

        $commonPaths = [
            '/usr/bin/soffice',
            '/usr/local/bin/soffice',
            '/opt/libreoffice*/program/soffice',
            '/usr/lib/libreoffice/program/soffice',
        ];

        foreach ($commonPaths as $pattern) {
            if (strpos($pattern, '*') !== false) {
                $matches = glob($pattern);
                if (!empty($matches)) {
                    return reset($matches);
                }
            } elseif (file_exists($pattern)) {
                return $pattern;
            }
        }

        return null;
    }

    /**
     * Procura o LibreOffice no macOS.
     */
    protected function findLibreOfficeOnMac(): ?string
    {
        $appPath = '/Applications/LibreOffice.app/Contents/MacOS/soffice';
        if (file_exists($appPath)) {
            return $appPath;
        }

        $homeAppPath = getenv('HOME') . '/Applications/LibreOffice.app/Contents/MacOS/soffice';
        if (file_exists($homeAppPath)) {
            return $homeAppPath;
        }

        return $this->findBinaryInPath('soffice');
    }

    /**
     * Verifica se o diretório de destino existe e é gravável
     */
    protected function ensureDirectoryWritable(string $dir): void
    {
        if (!is_dir($dir)) {
            if (!mkdir($dir, 0777, true) && !is_dir($dir)) {
                throw new \RuntimeException("Não foi possível criar o diretório de destino: {$dir}");
            }
        }

        if (!is_writable($dir)) {
            throw new \RuntimeException("Diretório de destino sem permissão de gravação: {$dir}");
        }
    }

    /**
     * Escapa caminho do Windows
     */
    protected function escapeWindowsPath(string $path): string
    {
        if (preg_match('/^".*"$/', $path)) {
            return $path;
        }
        return '"' . $path . '"';
    }

    /**
     * Procura o LibreOffice no Windows
     */
    protected function findLibreOfficeOnWindows(): ?string
    {
        $output = [];
        exec('where soffice 2>nul', $output, $returnCode);
        if ($returnCode === 0 && !empty($output[0])) {
            return $this->escapeWindowsPath($output[0]);
        }

        $possiblePaths = [
            'C:\\Program Files\\LibreOffice\\program\\soffice.exe',
            'C:\\Program Files (x86)\\LibreOffice\\program\\soffice.exe',
            'C:\\Program Files\\LibreOffice*\\program\\soffice.exe',
            'C:\\Program Files (x86)\\LibreOffice*\\program\\soffice.exe',
        ];

        foreach ($possiblePaths as $pattern) {
            if (strpos($pattern, '*') !== false) {
                $matches = glob($pattern);
                if (!empty($matches)) {
                    return $this->escapeWindowsPath(reset($matches));
                }
            } elseif (file_exists($pattern)) {
                return $this->escapeWindowsPath($pattern);
            }
        }

        return null;
    }
}