<?php

namespace FragosoSoftware\FileConverter\Infrastructure\Conversion;

use FragosoSoftware\FileConverter\Config\ConverterConfig;

/**
 * Cliente para comunicação com LibreOffice externo (sidecar container)
 */
class LibreOfficeClient
{
    protected ConverterConfig $config;
    
    /** @var resource|null */
    private $socket = null;
    
    protected bool $connected = false;

    public function __construct(?ConverterConfig $config = null)
    {
        $this->config = $config ?? ConverterConfig::getInstance();
    }

    /**
     * Conecta ao LibreOffice externo
     *
     * @throws \RuntimeException
     */
    protected function connect(): void
    {
        if ($this->connected && $this->socket !== null) {
            return;
        }

        $host = $this->config->getLibreOfficeHost();
        $port = $this->config->getLibreOfficePort();
        $timeout = $this->config->getLibreOfficeTimeout();

        $errno = null;
        $errstr = null;
        $this->socket = @fsockopen($host, $port, $errno, $errstr, $timeout);
        
        if ($this->socket === false) {
            throw new \RuntimeException(
                "Não foi possível conectar ao LibreOffice externo em {$host}:{$port}. Erro: {$errstr} ({$errno})"
            );
        }

        $this->connected = true;
    }

    /**
     * Desconecta
     */
    protected function disconnect(): void
    {
        if ($this->socket !== null) {
            fclose($this->socket);
            $this->socket = null;
            $this->connected = false;
        }
    }

    /**
     * Converte arquivo usando LibreOffice externo via socket
     *
     * @param string $sourcePath
     * @param string $destinationPath
     * @throws \RuntimeException
     */
    public function convert(string $sourcePath, string $destinationPath): void
    {
        // Para usar via socket, precisaríamos implementar a comunicação UNO
        // Como é complexo, vamos usar uma abordagem mais simples:
        // O LibreOffice externo pode ser chamado via linha de comando apontando para o host
        
        $outputDir = dirname($destinationPath);
        $this->ensureDirectoryWritable($outputDir);

        // Verifica se o binary local está disponível para se comunicar com o socket remoto
        if (!$this->isExecAvailable()) {
            throw new \RuntimeException('exec() function is not available for LibreOffice external conversion');
        }

        // Usa o binary local para se comunicar com o socket remoto
        $command = sprintf(
            'soffice --headless --norestore --nodefault --nofirststartwizard --invisible '
            . '--accept="socket,host=%s,port=%s;urp;" '
            . '--convert-to pdf --outdir %s %s 2>&1',
            $this->config->getLibreOfficeHost(),
            $this->config->getLibreOfficePort(),
            escapeshellarg($outputDir),
            escapeshellarg($sourcePath)
        );
        
        $output = [];
        $returnCode = 0;
        exec($command, $output, $returnCode);
        
        if ($returnCode !== 0) {
            throw new \RuntimeException(
                'LibreOffice external conversion failed: ' . implode("\n", $output)
            );
        }
        
        // Verifica se o arquivo foi gerado
        $generatedFile = $outputDir . DIRECTORY_SEPARATOR . pathinfo($sourcePath, PATHINFO_FILENAME) . '.pdf';
        
        if (!file_exists($generatedFile)) {
            throw new \RuntimeException('PDF file not generated by LibreOffice external');
        }
        
        if ($generatedFile !== $destinationPath) {
            if (!rename($generatedFile, $destinationPath)) {
                throw new \RuntimeException('Could not move generated PDF to destination');
            }
        }
    }

    /**
     * Verifica se o serviço externo está disponível
     */
    public function isAvailable(): bool
    {
        try {
            $this->connect();
            $this->disconnect();
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Verifica se a função exec() está disponível
     */
    protected function isExecAvailable(): bool
    {
        if (!function_exists('exec')) {
            return false;
        }
        
        $disabled = explode(',', ini_get('disable_functions'));
        return !in_array('exec', array_map('trim', $disabled), true);
    }

    /**
     * Verifica se o diretório é gravável
     */
    protected function ensureDirectoryWritable(string $dir): void
    {
        if (!is_dir($dir)) {
            if (!mkdir($dir, 0777, true) && !is_dir($dir)) {
                throw new \RuntimeException("Não foi possível criar o diretório: {$dir}");
            }
        }

        if (!is_writable($dir)) {
            throw new \RuntimeException("Diretório sem permissão de gravação: {$dir}");
        }
    }
}