<?php

namespace FragosoSoftware\FileConverter\Infrastructure\Conversion;

use FragosoSoftware\FileConverter\Core\Conversion\AbstractConverter;
use PhpOffice\PhpWord\IOFactory as WordIOFactory;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * Converte ODT para PDF.
 * Prioridade: LibreOffice
 * Fallback: PhpWord + Dompdf
 */
class OdtToPdfConverter extends AbstractConverter
{
    public function convert(string $sourcePath, string $destinationPath): void
    {
        $this->ensureFileReadable($sourcePath);
        $this->ensureDirectoryWritable(dirname($destinationPath));

        if ($this->canUseLibreOffice()) {
            try {
                $this->convertWithLibreOffice($sourcePath, $destinationPath);
                return;
            } catch (\RuntimeException $e) {
                error_log(
                    'LibreOffice ODT conversion failed, falling back: ' . $e->getMessage()
                );
            }
        }

        $this->convertWithPhpWord($sourcePath, $destinationPath);
    }

    protected function convertWithLibreOffice(string $sourcePath, string $destinationPath): void
    {
        $outputDir = dirname($destinationPath);

        $command = sprintf(
            'soffice --headless --convert-to pdf --outdir %s %s 2>&1',
            escapeshellarg($outputDir),
            escapeshellarg($sourcePath)
        );

        exec($command, $output, $resultCode);

        if ($resultCode !== 0) {
            throw new \RuntimeException(
                'LibreOffice conversion failed: ' . implode("\n", $output)
            );
        }

        $generatedPdf = $outputDir . '/' . pathinfo($sourcePath, PATHINFO_FILENAME) . '.pdf';

        if (!file_exists($generatedPdf)) {
            throw new \RuntimeException('Expected PDF not generated by LibreOffice.');
        }

        rename($generatedPdf, $destinationPath);
    }

    protected function convertWithPhpWord(string $sourcePath, string $destinationPath): void
    {
        $phpWord = WordIOFactory::load($sourcePath);

        $htmlWriter = WordIOFactory::createWriter($phpWord, 'HTML');

        $tempHtml = tempnam(sys_get_temp_dir(), 'odt_html_') . '.html';

        $htmlWriter->save($tempHtml);

        $dompdf = new Dompdf($this->getOptions());
        $dompdf->loadHtml(file_get_contents($tempHtml));
        $dompdf->render();

        file_put_contents($destinationPath, $dompdf->output());

        unlink($tempHtml);
    }

    protected function getOptions(): Options
    {
        $options = new Options();
        $options->set('isRemoteEnabled', true);

        return $options;
    }

    protected function canUseLibreOffice(): bool
    {
        if (!function_exists('exec')) {
            return false;
        }

        exec('soffice --version 2>&1', $output, $code);

        return $code === 0;
    }
}