<?php

namespace FragosoSoftware\FileConverter\Infrastructure\Conversion;

use FragosoSoftware\FileConverter\Core\Conversion\AbstractConverter;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Settings;
use Dompdf\Dompdf;

/**
 * Converte arquivos RTF para PDF usando LibreOffice (preferencial) ou PhpWord + Dompdf (fallback).
 * A classe detecta automaticamente a localização do LibreOffice em diferentes sistemas operacionais
 * e verifica se a função exec() está disponível antes de tentar usá-la.
 */
class RtfToPdfConverter extends AbstractConverter
{
    /**
     * {@inheritdoc}
     */
    public function convert(string $sourcePath, string $destinationPath): void
    {
        $this->ensureFileReadable($sourcePath);
        $this->ensureDirectoryWritable(dirname($destinationPath));

        if ($this->canUseLibreOffice()) {
            try {
                $this->convertWithLibreOffice($sourcePath, $destinationPath);
                return;
            } catch (\RuntimeException $e) {
                // Se a conversão com LibreOffice falhar, tenta fallback com PhpWord
                error_log('LibreOffice conversion failed, falling back to PhpWord: ' . $e->getMessage());
            }
        }

        $this->convertWithPhpWord($sourcePath, $destinationPath);
    }
    
    
    /**
     * Converte usando LibreOffice (linha de comando).
     *
     * @param string $sourcePath
     * @param string $destinationPath
     * @throws \RuntimeException
     */
    private function convertWithLibreOffice(string $sourcePath, string $destinationPath): void
    {
        $soffice = $this->findLibreOfficeBinary();
        if ($soffice === null) {
            throw new \RuntimeException('LibreOffice binary not found.');
        }

        $outputDir = dirname($destinationPath);
        // Garante que o diretório existe (já foi verificado antes)
        $this->ensureDirectoryWritable($outputDir);

        // Constrói o comando com escapes adequados
        $command = sprintf(
            '%s --headless --convert-to pdf --outdir %s %s',
            $soffice,
            escapeshellarg($outputDir),
            escapeshellarg($sourcePath)
        );

        // Executa o comando
        $output = [];
        $returnCode = 0;
        exec($command, $output, $returnCode);

        if ($returnCode !== 0) {
            throw new \RuntimeException(
                'LibreOffice conversion failed. Command: ' . $command . ' Output: ' . implode("\n", $output)
            );
        }

        // O LibreOffice gera o PDF no diretório de saída com o mesmo nome base do arquivo de origem
        $generatedFile = $outputDir . DIRECTORY_SEPARATOR . pathinfo($sourcePath, PATHINFO_FILENAME) . '.pdf';

        if (!file_exists($generatedFile)) {
            throw new \RuntimeException('PDF file not generated by LibreOffice.');
        }

        // Move o arquivo gerado para o destino final (se já estiver no local correto, não faz nada)
        if ($generatedFile !== $destinationPath) {
            if (!rename($generatedFile, $destinationPath)) {
                throw new \RuntimeException('Could not move generated PDF to destination.');
            }
        }
    }

    /**
     * Converte usando PhpWord + Dompdf (fallback).
     *
     * @param string $sourcePath
     * @param string $destinationPath
     * @throws \RuntimeException
     */
    private function convertWithPhpWord(string $sourcePath, string $destinationPath): void
    {
        try {
            // Configura o renderizador de PDF para Dompdf
            Settings::setPdfRendererName(Settings::PDF_RENDERER_DOMPDF);
            // Localiza o caminho do Dompdf (assumindo que está instalado via Composer)
            $dompdfReflection = new \ReflectionClass(Dompdf::class);
            $dompdfPath = dirname($dompdfReflection->getFileName(), 2); // sobe dois níveis para a raiz do pacote
            Settings::setPdfRendererPath($dompdfPath);

            // Carrega o documento RTF
            $phpWord = IOFactory::load($sourcePath, 'RTF');

            // Salva como PDF
            $writer = IOFactory::createWriter($phpWord, 'PDF');
            $writer->save($destinationPath);
        } catch (\Exception $e) {
            throw new \RuntimeException('PhpWord conversion failed: ' . $e->getMessage(), 0, $e);
        }
    }
}